name: GeneXpress
channels:
  - plotly
  - anaconda
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - _r-mutex=1.0.1
  - alabaster=0.7.12
  - appdirs=1.4.3
  - appnope=0.1.0
  - asn1crypto=1.3.0
  - attrs=19.3.0
  - babel=2.8.0
  - backcall=0.1.0
  - beautifulsoup4=4.9.0
  - bioconductor-affxparser=1.58.0
  - bioconductor-affy=1.64.0
  - bioconductor-affycoretools=1.58.0
  - bioconductor-affyio=1.56.0
  - bioconductor-annotate=1.64.0
  - bioconductor-annotationdbi=1.48.0
  - bioconductor-annotationfilter=1.10.0
  - bioconductor-annotationforge=1.28.0
  - bioconductor-arraytools=1.46.0
  - bioconductor-ballgown=2.18.0
  - bioconductor-biobase=2.46.0
  - bioconductor-biocfilecache=1.10.0
  - bioconductor-biocgenerics=0.32.0
  - bioconductor-biocparallel=1.20.0
  - bioconductor-biomart=2.42.0
  - bioconductor-biostrings=2.54.0
  - bioconductor-biovizbase=1.34.0
  - bioconductor-bsgenome=1.54.0
  - bioconductor-bumphunter=1.28.0
  - bioconductor-category=2.52.0
  - bioconductor-delayedarray=0.12.0
  - bioconductor-delayedmatrixstats=1.8.0
  - bioconductor-deseq2=1.26.0
  - bioconductor-edger=3.28.0
  - bioconductor-ensembldb=2.10.0
  - bioconductor-fdb.infiniummethylation.hg19=2.2.0
  - bioconductor-gcrma=2.58.0
  - bioconductor-genefilter=1.68.0
  - bioconductor-geneplotter=1.64.0
  - bioconductor-genomeinfodb=1.22.0
  - bioconductor-genomeinfodbdata=1.2.2
  - bioconductor-genomicalignments=1.22.0
  - bioconductor-genomicfeatures=1.38.0
  - bioconductor-genomicranges=1.38.0
  - bioconductor-geoquery=2.54.0
  - bioconductor-ggbio=1.34.0
  - bioconductor-go.db=3.10.0
  - bioconductor-gostats=2.52.0
  - bioconductor-graph=1.64.0
  - bioconductor-gseabase=1.48.0
  - bioconductor-hdf5array=1.14.0
  - bioconductor-illuminaio=0.28.0
  - bioconductor-iranges=2.20.0
  - bioconductor-limma=3.42.0
  - bioconductor-lumi=2.38.0
  - bioconductor-methylumi=2.32.0
  - bioconductor-minfi=1.32.0
  - bioconductor-multtest=2.42.0
  - bioconductor-oligo=1.50.0
  - bioconductor-oligoclasses=1.48.0
  - bioconductor-org.hs.eg.db=3.10.0
  - bioconductor-organismdbi=1.28.0
  - bioconductor-pd.hugene.2.1.st=3.14.1
  - bioconductor-pfam.db=3.10.0
  - bioconductor-preprocesscore=1.48.0
  - bioconductor-protgenerics=1.18.0
  - bioconductor-rbgl=1.62.1
  - bioconductor-reportingtools=2.26.0
  - bioconductor-rgraphviz=2.30.0
  - bioconductor-rhdf5=2.30.0
  - bioconductor-rhdf5lib=1.8.0
  - bioconductor-rhtslib=1.18.0
  - bioconductor-rsamtools=2.2.0
  - bioconductor-rtracklayer=1.46.0
  - bioconductor-s4vectors=0.24.0
  - bioconductor-siggenes=1.60.0
  - bioconductor-summarizedexperiment=1.16.0
  - bioconductor-sva=3.34.0
  - bioconductor-txdb.hsapiens.ucsc.hg19.knowngene=3.2.2
  - bioconductor-variantannotation=1.32.0
  - bioconductor-xvector=0.26.0
  - bioconductor-zlibbioc=1.32.0
  - biopython=1.76
  - bioservices=1.7.4
  - biothings_client=0.2.1
  - blas=2.14
  - bleach=3.1.4
  - brotlipy=0.7.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - ca-certificates=2020.4.5.2
  - cairo=1.16.0
  - cctools=927.0.2
  - certifi=2020.4.5.2
  - cffi=1.14.0
  - chardet=3.0.4
  - chart-studio=1.1.0
  - clang=9.0.1
  - clang-tools=9.0.1
  - clang_osx-64=9.0.1
  - clangxx=9.0.1
  - clangxx_osx-64=9.0.1
  - colorama=0.4.3
  - colorlog=4.1.0
  - compiler-rt=9.0.1
  - compiler-rt_osx-64=9.0.1
  - conda=4.8.3
  - conda-build=3.19.2
  - conda-package-handling=1.6.1
  - cryptography=2.9.2
  - curl=7.69.1
  - cycler=0.10.0
  - dbus=1.13.14
  - decorator=4.4.2
  - defusedxml=0.6.0
  - docker-py=4.2.1
  - docker-pycreds=0.4.0
  - docutils=0.16
  - easydev=0.9.38
  - entrypoints=0.3
  - escapism=1.0.1
  - expat=2.2.9
  - filelock=3.0.12
  - fontconfig=2.13.1
  - freetype=2.10.1
  - fribidi=1.0.9
  - gettext=0.19.8.1
  - gevent=20.5.0
  - gfortran_impl_osx-64=7.3.0
  - gfortran_osx-64=7.3.0
  - glib=2.64.2
  - glob2=0.7
  - gmp=6.2.0
  - graphite2=1.3.13
  - greenlet=0.4.15
  - grequests=0.6.0
  - gseapy=0.9.18
  - gsl=2.6
  - harfbuzz=2.4.0
  - html5lib=1.0.1
  - icu=64.2
  - idna=2.9
  - imagesize=1.2.0
  - importlib-metadata=1.6.0
  - importlib_metadata=1.6.0
  - ipykernel=5.2.1
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isl=0.19
  - jedi=0.17.0
  - jinja2=2.11.2
  - joblib=0.14.1
  - joypy=0.2.2
  - jpeg=9c
  - json5=0.9.4
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter-repo2docker=0.11.0
  - jupyter_client=6.1.3
  - jupyter_console=6.1.0
  - jupyter_contrib_core=0.3.3
  - jupyter_core=4.6.3
  - jupyter_nbextensions_configurator=0.4.1
  - jupyterlab=2.1.1
  - jupyterlab_server=1.1.1
  - kiwisolver=1.2.0
  - krb5=1.17.1
  - ld64=450.3
  - libarchive=3.4.2
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libcurl=7.69.1
  - libcxx=10.0.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=4.0.0
  - libiconv=1.15
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - liblief=0.10.1
  - libllvm10=10.0.0
  - libllvm9=9.0.1
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libpq=12.2
  - libsodium=1.0.17
  - libssh2=1.8.2
  - libtiff=4.1.0
  - libwebp-base=1.1.0
  - libxml2=2.9.10
  - libxslt=1.1.33
  - llvm-openmp=10.0.0
  - lxml=4.5.0
  - lz4-c=1.9.2
  - make=4.3
  - markupsafe=1.1.1
  - matplotlib=3.2.1
  - matplotlib-base=3.2.1
  - matplotlib-venn=0.11.5
  - mistune=0.8.4
  - more-itertools=8.2.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mygene=3.1.0
  - nbconvert=5.6.1
  - nbformat=5.0.6
  - ncurses=6.2
  - nomkl=3.0
  - notebook=6.0.3
  - nspr=4.22
  - nss=3.47
  - numpy=1.18.1
  - numpydoc=0.9.2
  - openblas=0.3.7
  - openssl=1.1.1g
  - packaging=20.3
  - pandas=1.0.3
  - pandoc=2.9.2.1
  - pandocfilters=1.4.2
  - pango=1.42.4
  - parso=0.7.0
  - patsy=0.5.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.1
  - pixman=0.38.0
  - pkginfo=1.5.0.1
  - plotly=4.7.1
  - pluggy=0.13.1
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.5
  - prompt_toolkit=3.0.5
  - psutil=5.7.0
  - ptyprocess=0.6.0
  - py=1.8.1
  - py-lief=0.10.1
  - pycosat=0.6.3
  - pycparser=2.20
  - pygments=2.6.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - pytest=5.4.2
  - python=3.7.6
  - python-dateutil=2.8.1
  - python-json-logger=0.1.11
  - python-libarchive-c=2.9
  - python_abi=3.7
  - pytz=2020.1
  - pyyaml=5.3.1
  - pyzmq=19.0.0
  - qt=5.12.5
  - qtconsole=4.7.4
  - qtpy=1.9.0
  - r=3.6
  - r-acepack=1.4.1
  - r-askpass=1.1
  - r-assertthat=0.2.1
  - r-backports=1.1.6
  - r-base=3.6.3
  - r-base64=2.0
  - r-base64enc=0.1_3
  - r-beanplot=1.2
  - r-bh=1.72.0_3
  - r-bibtex=0.4.2.2
  - r-biocmanager=1.30.10
  - r-bit=1.1_15.2
  - r-bit64=0.9_7
  - r-bitops=1.0_6
  - r-blob=1.2.1
  - r-boot=1.3_25
  - r-callr=3.4.3
  - r-catools=1.18.0
  - r-checkmate=2.0.0
  - r-class=7.3_17
  - r-cli=2.0.2
  - r-clipr=0.7.0
  - r-cluster=2.1.0
  - r-codetools=0.2_16
  - r-colorspace=1.4_1
  - r-crayon=1.3.4
  - r-curl=4.3
  - r-data.table=1.12.8
  - r-dbi=1.1.0
  - r-dbplyr=1.4.3
  - r-desc=1.2.0
  - r-dichromat=2.0_0
  - r-digest=0.6.25
  - r-dorng=1.8.2
  - r-dplyr=0.8.5
  - r-ellipsis=0.3.0
  - r-evaluate=0.14
  - r-fansi=0.4.1
  - r-farver=2.0.3
  - r-ff=2.2_14.2
  - r-foreach=1.5.0
  - r-foreign=0.8_76
  - r-formatr=1.7
  - r-formula=1.2_3
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-gdata=2.18.0
  - r-ggally=1.5.0
  - r-ggplot2=3.3.0
  - r-glue=1.4.0
  - r-gplots=3.0.3
  - r-gridextra=2.3
  - r-gtable=0.3.0
  - r-gtools=3.8.2
  - r-highr=0.8
  - r-hmisc=4.4_0
  - r-hms=0.5.3
  - r-htmltable=1.13.3
  - r-htmltools=0.4.0
  - r-htmlwidgets=1.5.1
  - r-httr=1.4.1
  - r-hwriter=1.3.2
  - r-isoband=0.2.1
  - r-iterators=1.0.12
  - r-jpeg=0.1_8.1
  - r-jsonlite=1.6.1
  - r-kernsmooth=2.23_17
  - r-knitr=1.28
  - r-labeling=0.3
  - r-lambda.r=1.2.4
  - r-lattice=0.20_41
  - r-latticeextra=0.6_29
  - r-lazyeval=0.2.2
  - r-lifecycle=0.2.0
  - r-locfit=1.5_9.4
  - r-magrittr=1.5
  - r-markdown=1.1
  - r-mass=7.3_51.6
  - r-matrix=1.2_18
  - r-matrixstats=0.56.0
  - r-mclust=5.4.6
  - r-memoise=1.1.0
  - r-mgcv=1.8_31
  - r-mime=0.9
  - r-munsell=0.5.0
  - r-nleqslv=3.3.2
  - r-nlme=3.1_147
  - r-nnet=7.3_14
  - r-nor1mix=1.3_0
  - r-openssl=1.4.1
  - r-pillar=1.4.3
  - r-pkgbuild=1.0.7
  - r-pkgconfig=2.0.3
  - r-pkgload=1.0.2
  - r-pkgmaker=0.31.1
  - r-plogr=0.2.0
  - r-plyr=1.8.6
  - r-png=0.1_7
  - r-praise=1.0.0
  - r-prettyunits=1.1.1
  - r-processx=3.4.2
  - r-progress=1.2.2
  - r-ps=1.3.2
  - r-purrr=0.3.4
  - r-quadprog=1.5_8
  - r-r.methodss3=1.8.0
  - r-r.oo=1.23.0
  - r-r.utils=2.9.2
  - r-r6=2.4.1
  - r-rappdirs=0.3.1
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.4.6
  - r-rcpparmadillo=0.9.870.2.0
  - r-rcurl=1.98_1.2
  - r-readr=1.3.1
  - r-recommended=3.6
  - r-registry=0.5_1
  - r-reshape=0.8.8
  - r-reshape2=1.4.4
  - r-rlang=0.4.5
  - r-rngtools=1.5
  - r-rpart=4.1_15
  - r-rprojroot=1.3_2
  - r-rsqlite=2.2.0
  - r-rstudioapi=0.11
  - r-scales=1.1.0
  - r-scrime=1.3.5
  - r-session=1.0.3
  - r-snow=0.4_3
  - r-spatial=7.3_12
  - r-stringi=1.4.6
  - r-stringr=1.4.0
  - r-survival=3.1_12
  - r-sys=3.3
  - r-testthat=2.3.2
  - r-tibble=3.0.1
  - r-tidyr=1.0.2
  - r-tidyselect=1.0.0
  - r-utf8=1.1.4
  - r-vctrs=0.2.4
  - r-viridis=0.5.1
  - r-viridislite=0.3.0
  - r-withr=2.2.0
  - r-xfun=0.13
  - r-xml=3.99_0.3
  - r-xml2=1.3.2
  - r-xtable=1.8_4
  - r-yaml=2.2.1
  - r-zeallot=0.1.0
  - readline=8.0
  - requests=2.23.0
  - requests-cache=0.5.0
  - retrying=1.3.3
  - ripgrep=12.1.1
  - rpy2=3.1.0
  - ruamel.yaml=0.16.10
  - ruamel.yaml.clib=0.2.0
  - ruamel_yaml=0.15.80
  - scikit-learn=0.22.2.post1
  - scipy=1.4.1
  - seaborn=0.10.0
  - semver=2.10.1
  - send2trash=1.5.0
  - setuptools=46.1.3
  - simplegeneric=0.8.1
  - six=1.14.0
  - snowballstemmer=2.0.0
  - soupsieve=2.0
  - sphinx=3.0.3
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sqlite=3.31.1
  - statsmodels=0.11.1
  - suds-jurko=0.6
  - tapi=1000.10.8
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.10
  - tktable=2.10
  - toml=0.10.1
  - tornado=6.0.4
  - traitlets=4.3.3
  - tzlocal=2.0.0
  - urllib3=1.25.9
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - websocket-client=0.57.0
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - wrapt=1.12.1
  - xz=5.2.5
  - yaml=0.2.4
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - keyring=
    - pyqt5-sip=
    - pyqtchart=
    - pyqtwebengine=
    - readme-renderer=
    - requests-toolbelt=
    - tqdm=
    - twine=

